### PR TITLE
fix: The replay button is broken

### PR DESCRIPTION
**Pull request by jnnklhmnn**
fixed bug regarding the playstate in the player component which prevented the replay button to work as expected

### CODE REVIEW

**Comment by alexander-heimbuch** [comment]
Thanks for the contribution, only an integration test for the control bar seems to be broken :)
If that is fixed I can merge it :P

**Comment by alexander-heimbuch** [comment]
Pretty sure this is just a timing issue. The back button get's disabled when playtime is 0. To show the progress bar play and pause is dispatched. Depending on the Cypress machine state some milliseconds may pass, which will cause the disabled state to be false. So my suggestion is to directly display the progress bar by dispatching `toggleProgressBar` and remove the cy.play and cy.pause from the test.

**Comment by jnnklhmnn** [comment]
seems legit, that would explain why the tests succeed on other machines, will fix it with the suggested solution

**Comment by jnnklhmnn** [comment]
I may be off track here but digging into this I’m not quite sure if the breaking test is testing quite the right thing.
So as far as I can see this test is breaking: https://github.com/podlove/podlove-web-player/blob/development/cypress/integration/controllbar.spec.js#L152

It is regarding the backbutton, and is checking for two things:
	- selectors.chapter.current().contains(this.chapters.chapters[0].title) working fine.
	- selectors.controls.chapters.back().should('have.attr', 'disabled') broken.

When the last chapter was reached or even ended, i would expect the back button to be enabled and allow the user to skip through the chapters backwards nevertheless the audio file ended or is playing the last chapter. The disabling makes sense for the forward button in this player state and is working fine.

So I’m left with the question, is the disabling of the back button when the last chapter was reached expected behaviour? Then it needs to be fixed in the code. If not, is this specific test appropriate?

Feedback on this highly appreciated :)

**Comment by alexander-heimbuch** [comment]
I think the title is simply a copy paste error from the next button test :/ The back button should be disabled on first chapter.

**Review by alexander-heimbuch — APPROVED** [review]

**Pull request merged**
